/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package day2;

import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import org.junit.Test;


import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void testChecksum() {
    URL resource = getClass().getClassLoader().getResource("test-input");
    List<String> input;
    try {
      input = Files.readAllLines(Paths.get(resource.getFile()));
    } catch (IOException e) {
      e.printStackTrace();
      input = List.of("");
    }
    assertEquals(12, App.checksum(input));
  }

  @Test
  public void testSearch() {
    URL resource = getClass().getClassLoader().getResource("test-input2");
    List<String> input;
    try {
      input = Files.readAllLines(Paths.get(resource.getFile()));
    } catch (IOException e) {
      e.printStackTrace();
      input = List.of("");
    }
    assertEquals("fgij", App.search(input));
  }
}
