/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package one;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class AdventDayTwo {
  public List<String> readInputFile(String filename) {
    File file = makeFileFromResourceName(filename);
    List<String> lines = new ArrayList<>();
    if (file != null) {
      BufferedReader br = createBufferedReader(file);
      if (br != null) {
        lines = br.lines().collect(Collectors.toList());
      }
    }
    return lines;
  }

  private BufferedReader createBufferedReader(File file) {
    try {
      return new BufferedReader(new FileReader(file));
    } catch (FileNotFoundException ex) {
      System.out.println("Error reading file");
      return null;
    }
  }

  private File makeFileFromResourceName(String filename) {
    try {
      URL resource = getClass().getClassLoader().getResource(filename);
      return new File(resource.toURI());
    } catch (URISyntaxException use) {
      System.out.println("Error creating URI from resource");
      return null;
    }
  }

  public static void main(String[] args) {
    // this is for calculating an answer using the input resource
    AdventDayTwo day2 = new AdventDayTwo();
    List<String> records = day2.readInputFile("input");

    int numberOfValidPasswords = 0;
    for (String record : records) {
      PasswordSet set = new PasswordSet(record);
      if (set.verify()) {
        numberOfValidPasswords++;
      }
    }

    System.out.println("Number of Valid Passwords: " + numberOfValidPasswords);
  }
}
