[package]
name = "DEC22"
version = "0.1.0"
authors = ["shep <pshepley@getguru.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
